export { default as Header } from "./Header"
export { default as Search } from "./Search"
export { default as ResultCard } from "./ResultCard"
export { default as FavouriteList } from "./FavouriteList"
export { default as FavouriteCard } from "./FavouriteCard"
export { default as TopRatedMovie } from "./TopRatedMovie"
export { Controls } from "./Controls"